theme: jekyll-theme-minimal

title: "My DevOps learning website"

author: "HansLu"

description: "This is the website I created for my DevOps course using GitHub Pages and Actions."

github:
  username: luhongxuan

plugins:
  - jekyll-seo-tag